### ISSUE TITLE
visualization of prediction of partnet segmentation

### ISSUE THREAD

**Issue by KangchengLiu** [zeliu98/CloserLook3D#13]
Any scripts for visualization of prediction of partnet segmentation as Fig 7 in your paper?

**Comment by mtli77** [comment]
> Any scripts for visualization of prediction of partnet segmentation as Fig 7 in your paper?

Hi @KangchengLiu 
Do you know, how to visualize the prediction of partner segmentation as Fig 7 in the paper?
