### ISSUE TITLE
'shadow_features' and 'shadow points' ?

### ISSUE THREAD

**Issue by linhaojia13** [zeliu98/CloserLook3D#14]
Hi @zeliu98 , thank you for your brilliant work!
In the file  'local_aggregation_operators.py': 

`shadow_features = tf.concat([features, tf.zeros_like(features[:1, :])], axis=0)`
`shadow_points = tf.concat([support_points, tf.zeros_like(support_points[:1, :])], axis=0)`

Why do you concatenate the zero vectors with the features and support_points to create the shadow ones?

**Comment by zeliu98** [comment]
Hi @linhaojia13, 
Thanks for your interest in our work. As for the `shadow_features` and `shadow_points`, they are paddings for variable-length points and neighborhoods.
