### ISSUE TITLE
Data error while pre-processing Aera5 of S3DIS

### ISSUE THREAD

**Issue by yzheng97** [zeliu98/CloserLook3D#15]
`
Cloud Area_5 - Room 21/68 : /media/data/S3DIS/Stanford3dDataset_v1.2/Area_5/office_19
Traceback (most recent call last):
  File "function/train_evaluate_s3dis.py", line 568, in <module>
    save_path = training(config)
  File "function/train_evaluate_s3dis.py", line 96, in training
    dataset = S3DISDataset(config, config.num_threads)
  File "/home/zy/3D/CloserLook3D/tensorflow/datasets/tf_s3dis_dataset.py", line 89, in __init__
    self.prepare_S3DIS_ply()
  File "/home/zy/3D/CloserLook3D/tensorflow/datasets/tf_s3dis_dataset.py", line 174, in prepare_S3DIS_ply
    object_data = np.array([[float(x) for x in line.split()] for line in f])
  File "/home/zy/3D/CloserLook3D/tensorflow/datasets/tf_s3dis_dataset.py", line 174, in <listcomp>
    object_data = np.array([[float(x) for x in line.split()] for line in f])
  File "/home/zy/3D/CloserLook3D/tensorflow/datasets/tf_s3dis_dataset.py", line 174, in <listcomp>
    object_data = np.array([[float(x) for x in line.split()] for line in f])
ValueError: could not convert string to float: '103.0\x100000'
`

**Comment by tangbohu** [comment]
> Solved

Could you share me the solution to resolove this issue?

**Comment by yzheng97** [comment]
> > Solved
> 
> Could you share me the solution to resolove this issue?

Just locate that file and manually correct the innormal number.

**Comment by tangbohu** [comment]
> > > Solved
> > 
> > 
> > Could you share me the solution to resolove this issue?
> 
> Just locate that file and manually correct the innormal number.

Thanks for your quick reply. I have found a ^P in the file. Thanks!

**Comment by tangbohu** [comment]
I locate the line "6.608000 12.546000 3.034000 116.000000 112.000000 103.00000". But it seems the number is OK?

**Comment by codename1995** [comment]
Tips for readers:

The unnormal number occurs in Line 323474 of the file S3DIS/Stanford3dDataset_v1.2/Area_5/office_19/Annotations/ceiling_1.txt
Correct the number 103.00000 to 103.000000.

**Comment by densechen** [comment]
I spend a long time to process the S3DIS dataset, is that right>?
```
====>min_potentials: [300.2869317967135, 300.28683857620433, 300.2906667716652, 300.2868395653529, 300.28667220968407][542/1764]: 4/1730517
====>min_potentials: [300.2869317967135, 300.28683857620433, 300.2906667716652, 300.2868395653529, 300.28730288229474][542/1765]: 1/321691====>min_potentials: [300.2869317967135, 300.2879575640328, 300.2906667716652, 300.2868395653529, 300.28730288229474][542/1766]: 3/482781
```

**Comment by FandosA** [comment]
> Tips for readers:
> 
> The unnormal number occurs in Line 323474 of the file S3DIS/Stanford3dDataset_v1.2/Area_5/office_19/Annotations/ceiling_1.txt Correct the number 103.0�0000 to 103.000000.

Thank you very much @codename1995!
