### ISSUE TITLE
How to choose radius, sampleDl, nsamples hyperparams

### ISSUE THREAD

**Issue by rakhimovv** [zeliu98/CloserLook3D#17]
Hello, thank you for the wonderful paper and code.

I am a relatively newbie in point cloud processing.
Could you please recommend please how to set `radius, sampleDl, nsamples` hyperparameters for my own point cloud dataset?

Maybe I can count some statistics for the dataset first, as the average distance to the 1st, 2nd, 3rd neighbor, and so on, and then somehow choose these hyperparams. What was your choosing strategy for datasets mentioned in the paper?

**Comment by zeliu98** [comment]
Hi @rakhimovv 
As for the `radius` and `sampleDl`, we simply follow the settings from KPConv(https://github.com/HuguesTHOMAS/KPConv). The `nsamples` are the averaged number of neighborhoods given other hyperparameters. However, the performance is not so sensitive to these hyperparameters.
