### ISSUE TITLE
Q. on Point-wise MLP methods

### ISSUE THREAD

**Issue by chaitjo** [zeliu98/CloserLook3D#26]
Thank you for the insightful work! I had a quick Q: in the Point-wise MLP methods, are you using the input/feature transform nets as proposed in PointNet? I was wondering if SotA/modern point-wise and graph-based approaches are still using these transform nets...

Additionally, in your paper p.12 eq.10, I would like to confirm: is it a typo that epsilon is being element-wise multiplied with f_{ij}? I assume that the correct operator is to multiply it with f_{j}?

**Comment by zeliu98** [comment]
Hi @chaitjo ,
We are not using the input/feature transform nets. And from my experience, most recent works are not using them either.

`f_{ij}` has the same meaning with  `f_{j}`,  representing the feature of the `j-th` point in `i` point's neighborhood, but in most case we omitted the mark `i` for brevity.

Best,
Ze
