### ISSUE TITLE
pytorch compile error: Couldn't work in Cuda 10.2, torch 1.5

### ISSUE THREAD

**Issue by cuge1995** [zeliu98/CloserLook3D#6]

**Comment by zeliu98** [comment]
Hi @cuge1995 
We haven't tested our code under cuda 10.2, pytorch 1.5 and I will check it.
You can use `cuda 10.1` and `pytorch 1.3` instead.

**Comment by zeliu98** [comment]
Thanks to @wangg12 and @paulwong16, we are now support `pytorch=1.5` now, please refer to the `pytorch-1.5` branch.
